### ISSUE TITLE
Object list for any model are not retrieved by the SPARQL service

### ISSUE THREAD

**Issue by colinRenaud** [OpenSILEX/opensilex-dev#5]
- Given some class **C** extending `SPARQLResourceModel` and **O** an instance of **C**
- Given **L** an attribute of the class **C**, which is a `List<? extends SPARQLResourceModel>`

- The creation of **O** with **L**  set, and the saving in the triple store is OK
- But when retrieving **O** by his URI with the `SPARQLService.getByURI()` method, the value of **L** is an empty List.
- This is not the case for other kind of attributes ( Primitives wrapper, URI, String, SPARQLResource, or List of Primitives wrapper/String)

**Comment by colinRenaud** [comment]
Example : 

`public class ExperimentModel extends SPARQLResourceModel implements ClassURIGenerator<ExperimentModel> { 
@SPARQLProperty(
            ontology = Oeso.class,
            property = "hasProject"
 )
 List<ProjectModel> projects = Collections.emptyList();}`

**Comment by colinRenaud** [comment]
- This problem comes from the `SPARQLClassQueryBuilder.getSelectBuilder(Node)` method and is also present in the ` SPARQLClassQueryBuilder.getCountBuilder(Node)` method. 
- The method define a graph for the whole SELECT query instead of setting a graph only for the WHERE parts

**Comment by vincentmigot** [comment]
Cloed by https://github.com/OpenSILEX/opensilex-dev/commit/feaf07ca7ac1829bd94d868a49ab7f4b0d86b311
